# Generated by Django 5.2.7 on 2025-10-31 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationaction',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='moderationaction',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='moderationaction',
            name='target_content_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='suppressed_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam or promotional'), ('off_topic', 'Off-topic'), ('incivility', 'Incivility/harassment'), ('policy', 'Policy violation'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='comment',
            name='suppressed_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam or promotional'), ('off_topic', 'Off-topic'), ('incivility', 'Incivility/harassment'), ('policy', 'Policy violation'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='media',
            name='app_media_target__4db655_idx',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commented_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='filetype',
        ),
        migrations.RemoveField(
            model_name='media',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='target_object_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_avatar',
        ),
        migrations.AddField(
            model_name='media',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.comment'),
        ),
        migrations.AddField(
            model_name='media',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.post'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['post'], name='app_media_post_id_7ec320_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['comment'], name='app_media_comment_f4f71c_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('comment__isnull', True)), models.Q(('post__isnull', True), ('comment__isnull', False)), _connector='OR'), name='media_exactly_one_target'),
        ),
        migrations.DeleteModel(
            name='ModerationAction',
        ),
        migrations.DeleteModel(
            name='SuppressionReason',
        ),
    ]
