# app/robot-models.py
# Generated by: GPT-5 Thinking (ChatGPT)
# Prompt used:
# """
# Using the following application spec, write a Django models.py that:
#  - uses Django's auth_user for authentication,
#  - supports two user roles (serf, administrator),
#  - supports posts and comments,
#  - supports moderation with reasons (admins can hide posts/comments; authors/admins can still see),
#  - supports user avatars (image upload),
#  - supports media attachments to posts and comments (images),
#  - stores enough info for an admin dashboard to report counts and byte volumes for 1/7/30 days,
#  - and runs cleanly with makemigrations/migrate.
# Keep the model straightforward and avoid Django contenttypes; use explicit nullable FKs instead.
# """

from __future__ import annotations
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.core.validators import FileExtensionValidator

User = get_user_model()


class UserType(models.Model):
    SERF = "serf"
    ADMIN = "admin"
    ROLE_CHOICES = [(SERF, "Serf"), (ADMIN, "Administrator")]
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="usertype")
    role = models.CharField(max_length=16, choices=ROLE_CHOICES, default=SERF)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    bio = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)


class SuppressionReason(models.Model):
    code = models.SlugField(max_length=64, unique=True)
    title = models.CharField(max_length=128)
    description = models.TextField()
    active = models.BooleanField(default=True)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="robot_posts")
    body = models.TextField()
    body_bytes = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    is_suppressed = models.BooleanField(default=False, db_index=True)
    suppressed_reason = models.ForeignKey(SuppressionReason, null=True, blank=True, on_delete=models.SET_NULL)
    suppressed_message_to_author = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self.body_bytes = len(self.body.encode("utf-8")) if self.body else 0
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="robot_comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="robot_comments")
    body = models.TextField()
    body_bytes = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    is_suppressed = models.BooleanField(default=False, db_index=True)
    suppressed_reason = models.ForeignKey(SuppressionReason, null=True, blank=True, on_delete=models.SET_NULL)
    suppressed_message_to_author = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self.body_bytes = len(self.body.encode("utf-8")) if self.body else 0
        super().save(*args, **kwargs)


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="robot_avatars")
    image = models.ImageField(
        upload_to="avatars/",
        validators=[FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"])]
    )
    is_active = models.BooleanField(default=True)
    image_bytes = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            self.image_bytes = self.image.size or 0
        except Exception:
            self.image_bytes = 0
        super().save(update_fields=["image_bytes"])


class Media(models.Model):
    """Simpler design: explicit nullable FKs instead of GenericForeignKey."""
    IMAGE = "image"
    FILETYPE_CHOICES = [(IMAGE, "Image")]

    uploader = models.ForeignKey(User, on_delete=models.CASCADE, related_name="robot_media")
    filetype = models.CharField(max_length=16, choices=FILETYPE_CHOICES, default=IMAGE)
    file = models.FileField(
        upload_to="media/",
        validators=[FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"])]
    )
    file_bytes = models.PositiveIntegerField(default=0)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE, related_name="media")
    comment = models.ForeignKey(Comment, null=True, blank=True, on_delete=models.CASCADE, related_name="media")
    created_at = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            self.file_bytes = self.file.size or 0
        except Exception:
            self.file_bytes = 0
        super().save(update_fields=["file_bytes"])


class ModerationAction(models.Model):
    ACTION_CHOICES = [
        ("hide_post", "Hide post"),
        ("hide_comment", "Hide comment"),
        ("unhide_post", "Unhide post"),
        ("unhide_comment", "Unhide comment"),
    ]
    moderator = models.ForeignKey(User, on_delete=models.PROTECT, related_name="robot_moderation_actions")
    action = models.CharField(max_length=32, choices=ACTION_CHOICES)
    reason = models.ForeignKey(SuppressionReason, null=True, blank=True, on_delete=models.SET_NULL)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE, related_name="moderation_actions")
    comment = models.ForeignKey(Comment, null=True, blank=True, on_delete=models.CASCADE, related_name="moderation_actions")
    message_to_author = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)

